export const SET_CURRENCIES = 'SET_CURRENCIES';
export const SET_CURRENCIES_RATE = 'SET_CURRENCIES_RATE';
export const SET_EXCHANGE_RATE = 'SET_EXCHANGE_RATE';
export const SET_CONVERTER_STATUS = 'SET_CONVERTER_STATUS';
export const SET_CURRENCIES_RATE_STATUS = 'SET_CURRENCIES_RATE_STATUS';